name: Update Time on Site

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час
  workflow_dispatch:     # Позволяет запускать вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Права на запись в репозиторий

    steps:
      - name: Скачиваем код репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Запускаем скрипт обновления времени
        run: python time_updater.py

      - name: Сохраняем и публикуем изменения
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update time [skip ci]" || exit 0
          git push
